name: Build and Release for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js 16
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build getEmail
        run: pkg getEmail.js --target node16-win-x64 -o getEmail.exe

      - name: Build readCode
        run: pkg readCode.js --target node16-win-x64 -o readCode.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            getEmail.exe
            readCode.exe
          tag_name: v1.0.0
          release_name: Release 1.0.0
          draft: false
          prerelease: false